### ISSUE TITLE
模型始终只预测一个类别

### ISSUE THREAD

**Issue by hoorayrui** [yangdai97/MultiChannelSleepNet#1]
hi！作者您好！
感谢您公开的代码，对我提供了很大的帮助。
但是我有一个问题，该代码在2013版本的数据集中始终不拟合，预测值的输出始终是同一个类别。请问你知道是什么问题吗？

**Comment by hoorayrui** [comment]
解决了！

**Comment by chauncy294** [comment]
> 解决了！

请问一下怎么解决的，我也遇到同样的情况

**Comment by hoorayrui** [comment]
> > 解决了！
> 
> 请问一下怎么解决的，我也遇到同样的情况

数据和标签没对应上，或者数据处理的有问题。都会导致这个情况

**Comment by chauncy294** [comment]
> > > 解决了！
> > 
> > 
> > 请问一下怎么解决的，我也遇到同样的情况
> 
> 数据和标签没对应上，或者数据处理的有问题。都会导致这个情况

感谢，发现问题了

**Comment by guoooooo** [comment]
> 解决了！

hello，方便细说一下如何解决的么

**Comment by hoorayrui** [comment]
同时进到for循环的数据和标签是否没对应上，如果是这样的话你对数据和标签sort一下试试
________________________________
发件人: guoooooo ***@***.***>
发送时间: 2024年5月31日 9:58
收件人: yangdai97/MultiChannelSleepNet ***@***.***>
抄送: hoorayrui ***@***.***>; State change ***@***.***>
主题: Re: [yangdai97/MultiChannelSleepNet] 模型始终只预测一个类别 (Issue #1)


解决了！

hello，方便细说一下如何解决的么

―

**Comment by aoee8899** [comment]
Hello, 

您是如何对标签进行排序的？

**Comment by hoorayrui** [comment]
> Hello,
> 
> 您是如何对标签进行排序的？
加载文件的时候sort一下

**Comment by aoee8899** [comment]
Ǹg, hǎo de, wǒ huì shì shì, dànshì shì shàngshēng háishì xiàjiàng
